options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  substitutionOption: "ALLOW_LOOSE"
  diskSizeGb: 50

substitutions:
  _REGION: "europe-west4"
  _SERVICE_NAME: "snow-flow-codespace"
  _ARTIFACT_REGISTRY_REPO: "snow-flow-enterprise"
  _MIN_INSTANCES: "1"
  _MAX_INSTANCES: "10"
  _MEMORY: "4Gi"
  _CPU: "2"
  _CONCURRENCY: "1"
  _TIMEOUT: "3600s"

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "pull-cache"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest || true

  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - "build"
      - "-f"
      - "Dockerfile.codespace"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest"
      - "--no-cache"
      - "."
    waitFor: ["pull-cache"]
    timeout: "1500s"

  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker push ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA &
        docker push ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest &
        wait
    waitFor: ["build-image"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-cloud-run"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --concurrency=${_CONCURRENCY} \
          --timeout=${_TIMEOUT} \
          --port=8080 \
          --session-affinity \
          --set-env-vars="PASSWORD=snowflow"
    waitFor: ["push-image"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "verify-deployment"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "Service URL: $$SERVICE_URL"

        for i in {1..6}; do
          echo "Health check attempt $$i/6..."
          HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" "$$SERVICE_URL/" 2>/dev/null)
          if [ "$$HTTP_CODE" = "200" ] || [ "$$HTTP_CODE" = "302" ]; then
            echo "code-server health check passed!"
            exit 0
          fi
          echo "Got HTTP $$HTTP_CODE, waiting 5 seconds..."
          sleep 5
        done

        echo "code-server health check failed after 30 seconds"
        exit 1
    waitFor: ["deploy-cloud-run"]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest"

timeout: "900s"

tags:
  - "snow-flow"
  - "codespace"
  - "${_SERVICE_NAME}"
