# Snow-Flow Enterprise - Cloud Build Configuration
# Automatically deploys to Cloud Run on push to main or test branch

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/license-server:$BRANCH_NAME-$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/license-server:$BRANCH_NAME-latest'
      - '-f'
      - 'license-server/Dockerfile'
      - 'license-server'
    dir: 'enterprise'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/license-server'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run (test or production based on branch)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/license-server:$BRANCH_NAME-$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--set-env-vars=NODE_ENV=${_NODE_ENV}'
      - '--set-secrets=ADMIN_KEY=admin-key:latest'
    waitFor: ['push-image']

# Substitutions based on branch
substitutions:
  # Default values (overridden per branch)
  _REGION: 'europe-west1'
  _ARTIFACT_REGISTRY_REPO: 'snow-flow-enterprise'
  _SERVICE_NAME: 'snow-flow-license-server-${BRANCH_NAME}'
  _NODE_ENV: 'production'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

# Timeout: 20 minutes
timeout: 1200s

# Images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/license-server:$BRANCH_NAME-$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/license-server:$BRANCH_NAME-latest'
