# Docker Compose override for development environment
# This file is automatically loaded when running docker-compose up
# Provides development-specific configurations

version: '3.8'

services:
  # Development overrides for MCP services
  deployment-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3001:3001"  # Expose for direct access in development

  flow-composer-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3002:3002"

  intelligent-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3003:3003"

  update-set-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3004:3004"

  graph-memory-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3005:3005"

  operations-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3006:3006"

  platform-development-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3007:3007"

  integration-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3008:3008"

  automation-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3009:3009"

  security-compliance-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3010:3010"

  reporting-analytics-mcp:
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=development
    ports:
      - "3011:3011"

  # Development tools
  consul:
    environment:
      - CONSUL_LOG_LEVEL=debug
    volumes:
      - ./docker/consul/dev-config.json:/consul/config/dev-config.json:ro

  nginx-lb:
    volumes:
      - ./docker/nginx/templates:/etc/consul-template/templates:ro
      - ./logs/nginx:/var/log/nginx
    environment:
      - NGINX_LOG_LEVEL=debug
      - CONSUL_TEMPLATE_LOG_LEVEL=debug