# Kustomization configuration for ServiceNow MCP services
{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "servicenow-mcp",
  "resources": [
    "namespace.yaml",
    "configmap.yaml",
    "rbac.yaml",
    "infrastructure.yaml",
    "mcp-services.yaml",
    "monitoring.yaml",
    "ingress.yaml"
  ],
  "images": [
    {
      "name": "servicenow-mcp/deployment-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/flow-composer-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/intelligent-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/update-set-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/graph-memory-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/operations-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/platform-development-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/integration-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/automation-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/security-compliance-mcp",
      "newTag": "latest"
    },
    {
      "name": "servicenow-mcp/reporting-analytics-mcp",
      "newTag": "latest"
    }
  ],
  "replicas": [
    {
      "name": "deployment-mcp",
      "count": 2
    },
    {
      "name": "flow-composer-mcp",
      "count": 2
    },
    {
      "name": "intelligent-mcp",
      "count": 3
    },
    {
      "name": "update-set-mcp",
      "count": 2
    },
    {
      "name": "graph-memory-mcp",
      "count": 2
    },
    {
      "name": "operations-mcp",
      "count": 3
    },
    {
      "name": "platform-development-mcp",
      "count": 2
    },
    {
      "name": "integration-mcp",
      "count": 2
    },
    {
      "name": "automation-mcp",
      "count": 2
    },
    {
      "name": "security-compliance-mcp",
      "count": 2
    },
    {
      "name": "reporting-analytics-mcp",
      "count": 2
    }
  ],
  "commonLabels": {
    "app.kubernetes.io/part-of": "servicenow-mcp",
    "app.kubernetes.io/managed-by": "kustomize"
  }
}