# Kubernetes namespace for ServiceNow MCP services
apiVersion: v1
kind: Namespace
metadata:
  name: servicenow-mcp
  labels:
    name: servicenow-mcp
    app.kubernetes.io/name: servicenow-mcp
    app.kubernetes.io/component: namespace
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "ServiceNow Multi-Agent MCP Services"
    contact: "devops@company.com"
---
# Network policies for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mcp-network-policy
  namespace: servicenow-mcp
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic within namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: servicenow-mcp
  # Allow traffic from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  # Allow traffic from monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  # Allow all outbound traffic (for ServiceNow API calls)
  - {}
---
# Resource quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-resource-quota
  namespace: servicenow-mcp
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "10"
---
# Limit ranges
apiVersion: v1
kind: LimitRange
metadata:
  name: mcp-limit-range
  namespace: servicenow-mcp
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "250m"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim