name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please check all boxes that apply
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version of Snow-Flow
          required: false

  - type: input
    id: version
    attributes:
      label: Snow-Flow Version
      description: What version of Snow-Flow are you using?
      placeholder: "2.0.2"
    validations:
      required: true

  - type: input
    id: servicenow-version
    attributes:
      label: ServiceNow Version
      description: What version of ServiceNow are you connecting to?
      placeholder: "Washington, Vancouver, Utah, etc."

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "18.17.0"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Snow-Flow fails to authenticate with ServiceNow when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Run `snow-flow auth login`
        2. Enter valid OAuth credentials
        3. See error message...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Authentication should succeed and show 'Login successful'"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Error: OAuth authentication failed"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please include any relevant error messages or logs
      placeholder: |
        Error: Request failed with status code 401
        at ServiceNowClient.authenticate (...)
        ...
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any additional environment information
      placeholder: |
        OS: macOS 14.0
        Terminal: iTerm2
        Shell: zsh
        Claude Code version: Latest

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This started happening after upgrading from version 2.0.1"