name: 🐛 Bug Report
description: Create a report to help us improve Snow-Flow
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have tested with the latest version of Snow-Flow
          required: true
        - label: I have included all relevant information below
          required: true

  - type: input
    id: version
    attributes:
      label: Snow-Flow Version
      description: Which version of Snow-Flow are you using?
      placeholder: "1.4.6"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running Snow-Flow in?
      options:
        - Development
        - Production
        - Testing/Staging
        - Local machine
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "18.17.0"
    validations:
      required: true

  - type: input
    id: servicenow-version
    attributes:
      label: ServiceNow Version
      description: What version of ServiceNow are you connecting to?
      placeholder: "Vancouver, Washington, etc."
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I try to create a widget using snow-flow swarm 'create dashboard widget', the command fails with..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command: `snow-flow swarm "create incident dashboard"`
        2. Wait for agent spawning
        3. See error message
        4. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: "The widget should be created successfully and deployed to ServiceNow"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: "The command fails with authentication error..."
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, paste relevant error logs or console output
      render: shell
      placeholder: |
        [2024-01-15 10:30:45] ERROR: Failed to authenticate with ServiceNow
        [2024-01-15 10:30:45] ERROR: 401 Unauthorized - Check your credentials
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive information)
      render: bash
      placeholder: |
        # .env file (sensitive values removed)
        SNOW_INSTANCE=dev12345.service-now.com
        SNOW_AUTH_TYPE=oauth
        SNOW_FLOW_LOG_LEVEL=info
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This started happening after updating to version 1.4.6..."
    validations:
      required: false

  - type: checkboxes
    id: component
    attributes:
      label: Affected Components
      description: Which components are affected by this bug?
      options:
        - label: Widget Creator Agent
        - label: Queen Agent
        - label: Memory System
        - label: ServiceNow Authentication
        - label: MCP Servers
        - label: CLI Interface
        - label: Update Set Management
        - label: Multi-agent Coordination
        - label: Other (please specify in additional context)

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major functionality broken)
        - Medium (some functionality affected)
        - Low (minor inconvenience)
    validations:
      required: true

  - type: checkboxes
    id: willing-to-help
    attributes:
      label: Contribution
      description: Are you willing to help with this bug?
      options:
        - label: I can provide more information if needed
        - label: I can test potential fixes
        - label: I would like to work on fixing this bug
        - label: I can help with documentation updates