name: ✨ Feature Request
description: Suggest a new feature or enhancement for Snow-Flow
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand and evaluate your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with Snow-Flow's goals
          required: true
        - label: I have provided detailed information below
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Agent Type
        - ServiceNow Integration
        - Developer Experience
        - Performance Improvement
        - CLI Enhancement
        - Memory System
        - Authentication
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What's the current limitation?
      placeholder: "Currently, Snow-Flow cannot automatically generate test data for widgets, which makes it difficult to..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution. What would you like to see?
      placeholder: "I would like Snow-Flow to have a test data generator agent that can..."
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe this feature from a user's perspective
      placeholder: "As a ServiceNow developer, I want to automatically generate realistic test data so that I can..."
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. Widget testing: Generate sample incident records for dashboard widgets
        2. Flow testing: Create test users and approval chains
        3. Performance testing: Generate large datasets for stress testing
    validations:
      required: true

  - type: textarea
    id: proposed-api
    attributes:
      label: Proposed API/Interface
      description: If applicable, describe the proposed command-line interface or API
      render: bash
      placeholder: |
        # Example command
        snow-flow test-data generate --type incidents --count 100 --realistic

        # Example programmatic API
        const testData = await testDataAgent.generate({
          type: 'incidents',
          count: 100,
          realistic: true
        });
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: "I considered using ServiceNow's built-in test data, but it's limited in scope..."
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas would this feature impact?
      options:
        - label: Agent Coordination
        - label: ServiceNow API Integration
        - label: Memory System
        - label: CLI Interface
        - label: Authentication
        - label: Performance
        - label: Developer Experience
        - label: Testing
        - label: Documentation
        - label: Breaking Changes

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (would significantly improve workflow)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature? (optional)
      placeholder: "Next release, within 3 months, no rush, etc."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: "This feature would integrate well with the existing widget creator agent..."
    validations:
      required: false

  - type: checkboxes
    id: implementation-complexity
    attributes:
      label: Implementation Considerations
      description: Have you considered the implementation complexity?
      options:
        - label: This seems like a simple addition
        - label: This might require significant changes
        - label: This could have breaking changes
        - label: This needs careful architecture consideration
        - label: I'm not sure about the complexity

  - type: checkboxes
    id: willing-to-help
    attributes:
      label: Contribution
      description: Are you willing to help with this feature?
      options:
        - label: I can provide more detailed requirements
        - label: I can help with design and planning
        - label: I would like to implement this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How would you measure the success of this feature?
      placeholder: |
        - Reduces widget testing setup time by 80%
        - Generates realistic test data in under 30 seconds
        - Integrates seamlessly with existing snow-flow commands
        - Provides clear documentation and examples
    validations:
      required: false