name: "Snow-Flow GitHub Action"
description: "Run Snow-Flow in GitHub Actions workflows"
branding:
  icon: "code"
  color: "orange"

inputs:
  model:
    description: "Model to use"
    required: true

  agent:
    description: "Agent to use. Must be a primary agent. Falls back to default_agent from config or 'build' if not found."
    required: false

  share:
    description: "Share the snow-code session (defaults to true for public repos)"
    required: false

  prompt:
    description: "Custom prompt to override the default prompt"
    required: false

  use_github_token:
    description: "Use GITHUB_TOKEN directly instead of OpenCode App token exchange. When true, skips OIDC and uses the GITHUB_TOKEN env var."
    required: false
    default: "false"

  mentions:
    description: "Comma-separated list of trigger phrases (case-insensitive). Defaults to '/snow-code,/sc'"
    required: false

  oidc_base_url:
    description: "Base URL for OIDC token exchange API. Only required when running a custom GitHub App install. Defaults to https://api.snow-flow.dev"
    required: false

runs:
  using: "composite"
  steps:
    - name: Get snow-code version
      id: version
      shell: bash
      run: |
        VERSION=$(curl -sf https://api.github.com/repos/groeimetai/snow-flow/releases/latest | grep -o '"tag_name": *"[^"]*"' | cut -d'"' -f4)
        echo "version=${VERSION:-latest}" >> $GITHUB_OUTPUT

    - name: Cache snow-code
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.snow-code/bin
        key: snow-code-${{ runner.os }}-${{ runner.arch }}-${{ steps.version.outputs.version }}

    - name: Install snow-code
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: curl -fsSL https://snow-flow.dev/install | bash

    - name: Add snow-code to PATH
      shell: bash
      run: echo "$HOME/.snow-code/bin" >> $GITHUB_PATH

    - name: Run snow-code
      shell: bash
      id: run_snow_code
      run: snow-code github run
      env:
        MODEL: ${{ inputs.model }}
        AGENT: ${{ inputs.agent }}
        SHARE: ${{ inputs.share }}
        PROMPT: ${{ inputs.prompt }}
        USE_GITHUB_TOKEN: ${{ inputs.use_github_token }}
        MENTIONS: ${{ inputs.mentions }}
        OIDC_BASE_URL: ${{ inputs.oidc_base_url }}
