# Cloud Build configuration for PRODUCTION environment
# Triggers on push to 'main' branch
# Deploys to: license-server-prod

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/license-server:prod-$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/license-server:prod-latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/license-server:latest'
      - '-f'
      - 'license-server/Dockerfile'
      - './license-server'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/license-server:prod-$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/license-server:prod-latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/license-server:latest']

  # Step 3: Deploy to Cloud Run (PRODUCTION)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'license-server-prod'
      - '--image=gcr.io/$PROJECT_ID/license-server:prod-$SHORT_SHA'
      - '--region=europe-west4'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=1'              # Always warm (faster response)
      - '--max-instances=5'               # Auto-scale to 5 max
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300s'                  # 5 minute timeout
      - '--concurrency=80'
      - '--port=8080'
      - '--cpu-throttling'                # Throttle CPU when idle (cost efficient)
      - '--set-env-vars=NODE_ENV=production,LOG_LEVEL=info'
      - '--set-secrets=ADMIN_KEY=ADMIN_KEY:latest'
      - '--labels=environment=production,branch=main,managed-by=cloud-build'

  # Step 4: Output deployment URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "================================================"
        echo "🎉 PRODUCTION DEPLOYMENT SUCCESSFUL!"
        echo "================================================"
        URL=$(gcloud run services describe license-server-prod --region=europe-west4 --format="value(status.url)")
        echo "📍 Production URL: $URL"
        echo "🏥 Health Check: $URL/health"
        echo "📊 Logs: https://console.cloud.google.com/run/detail/europe-west4/license-server-prod/logs"
        echo "📈 Metrics: https://console.cloud.google.com/run/detail/europe-west4/license-server-prod/metrics"
        echo "================================================"
        echo "⚠️  REMINDER: Test the health endpoint before using!"
        echo "   curl $URL/health"
        echo "================================================"

  # Step 5: Run smoke test
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-f'
      - '-s'
      - '-o'
      - '/dev/null'
      - '-w'
      - 'Health check: %{http_code}\n'
      - '$(gcloud run services describe license-server-prod --region=europe-west4 --format="value(status.url)")/health'

images:
  - 'gcr.io/$PROJECT_ID/license-server:prod-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/license-server:prod-latest'
  - 'gcr.io/$PROJECT_ID/license-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Fast builds

timeout: '600s'  # 10 minute timeout
