#!/usr/bin/env node
/**
 * Syncs version.ts with the version from package.json
 * This runs via preversion hook to ensure version.ts is always up-to-date
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

const versionContent = `// Auto-generated by npm version command
export const VERSION = '${version}';
`;

fs.writeFileSync(versionTsPath, versionContent);
console.log(`✅ Synced version.ts to ${version}`);
